---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  ROLLBAR_ACCOUNT_READ_TOKEN: {{ required "rollbarAccountReadToken must be set" .Values.exporter.rollbarAccountReadToken }}
  {{- with .Values.exporter.rollbarAccountWriteToken }}
  ROLLBAR_ACCOUNT_WRITE_TOKEN: {{ . }}
  {{- end }}
  {{- with .Values.exporter.scrapeInterval }}
  SCRAPE_INTERVAL: {{ . }}
  {{- end }}
  {{- with .Values.exporter.maxItems }}
  MAX_ITEMS: {{ . }}
  {{- end }}
